
                        const database = [
                            {
                                id: 100,
                                category: "electronics",
                                subCategory: "phone",
                                productName: "Oppo A78 Smart Phone",
                                brand: "Oppo",
                                ModelName: "A78",
                                os: "Android 13.0",
                                manufacturer: "OPPO MOBILES INDIA PVT",
                                images: {
                                    imgUrl1: "/images/mobilesImages/oppo/oppo_A78/oPPO_A78_Aqua_Green.png",
                                    imgUrl2: "/images/mobilesImages/oppo/oppo_A78/oPPO_A78_Aqua_Green_img1.jpg",
                                    imgUrl3: "/images/mobilesImages/oppo/oppo_A78/oPPO_A78_Aqua_Green_img2.jpg",
                                    imgUrl4: "/images/mobilesImages/oppo/oppo_A78/oPPO_A78_Aqua_Green_img3.jpg",
                                    imgUrl5: "/images/mobilesImages/oppo/oppo_A78/oPPO_A78_Aqua_Green_img4.jpg",
                                    imgUrl6: "/images/mobilesImages/oppo/oppo_A78/oPPO_A78_Aqua_Green_img5.jpg",
                                },
                                discription: "OPPO A78 (Aqua Green, 8GB RAM, 128GB Storage) | 6.4 inch FHD+ AMOLED 90Hz Punch Hole Display | 5000 mAh Battery and 67W SUPERVOOC with No Cost EMI/Additional Exchange Offers",
                                about: [
                                    "6.4 inch FHD+ AMOLED 90Hz Punch Hole Display with 2400x1080 pixels & In-Display Fingerprint Sensor",
                                    "Big 5000 mAh Battery with 67W SUPERVOOC Charging",
                                    "Memory, Storage & SIM: 8 GB RAM (+ RAM expansion up to 8GB) | 128 GB ROM | Expandable Upto 1TB | Dual SIM Slot",
                                    "Dual Camera Setup: 50MP Main Camera (f/1.8 Aperture, FOV: 77 Degree, 5P Lens, Auto Focus",
                                    "8MP Front Camera: (f/2.0 Aperture, FOV: 83 Degree, 4P Lens), ",
                                ],
                                colour: ["Aqua Green"],
                                stock: "In stock",
                                stars: 3.8,
                                reviews: 202,
                                price: 17499,
                            },
                            {
                                id: 101,
                                category: "electronics",
                                subCategory: "phone",
                                productName: "Oppo A17k Smart phone",
                                brand: "Oppo",
                                ModelName: "A17k",
                                os: "Android 12.0",
                                manufacturer: "OPPO MOBILES INDIA PVT",
                                images: {
                                    imgUrl1: "/images/mobilesImages/oppo/oppo_A17k/oppo_A17K.png",
                                    imgUrl2: "/images/mobilesImages/oppo/oppo_A17k/oppo_A17K_img1.jpg",
                                    imgUrl3: "/images/mobilesImages/oppo/oppo_A17k/oppo_A17K_img2.jpg",
                                    imgUrl4: "/images/mobilesImages/oppo/oppo_A17k/oppo_A17K_img3.jpg",
                                    imgUrl5: "/images/mobilesImages/oppo/oppo_A17k/oppo_A17K_img4.jpg",
                                    imgUrl6: "/images/mobilesImages/oppo/oppo_A17k/oppo_A17K_img5.jpg",
                                },
                                discription: "Oppo A17k (Blue, 3GB RAM, 64GB Storage) with No Cost EMI/Additional Exchange Offers",
                                about: [
                                    "6.56 inch (16.66cm) HD+ Waterdrop Colour Rich Display with 1612x720 pixels | IPX4 Water Resistant | Side Fingerprint Sensor",
                                    "3 GB RAM (Up to 4GB Extended RAM)| 64 GB ROM | Dual Sim Slot + Micro SD with MediaTek P35 processor and long lasting 5000 mAh Battery",
                                    "5MP Front Camera | 8MP Rear Camera",
                                ],
                                colour: ["Blue"],
                                stock: "In stock",
                                stars: 4.0,
                                reviews: 381,
                                price: 8999,
                            },
                            {
                                id: 102,
                                category: "electronics",
                                subCategory: "phone",
                                productName: "Oppo F23 5G Smart Phone",
                                brand: "Oppo",
                                ModelName: "F23 5G",
                                os: "Android 13.0",
                                manufacturer: "OPPO MOBILES INDIA PVT",
                                images: {
                                    imgUrl1: "/images/mobilesImages/oppo/oppo_F23/oppo_F23_5G.png",
                                    imgUrl2: "/images/mobilesImages/oppo/oppo_F23/oppo_F23_5G_img1.jpg",
                                    imgUrl3: "/images/mobilesImages/oppo/oppo_F23/oppo_F23_5G_img2.jpg",
                                    imgUrl4: "/images/mobilesImages/oppo/oppo_F23/oppo_F23_5G_img3.jpg",
                                    imgUrl5: "/images/mobilesImages/oppo/oppo_F23/oppo_F23_5G_img4.jpg",
                                    imgUrl6: "/images/mobilesImages/oppo/oppo_F23/oppo_F23_5G_img5.jpg",
                                },
                                discription: "OPPO F23 5G (Bold Gold, 8GB RAM, 256GB Storage) | 5000 mAh Battery with 67W SUPERVOOC Charger | 64MP Rear Triple AI Camera with Microlens | 6.72 inch FHD+ 120Hz Display",
                                about: [
                                    "Memory, Storage & SIM: 8 GB RAM (+ RAM expansion up to 8GB) | 256 GB ROM | Expandable Upto 1TB | Dual Hybrid 5G SIM Slot",
                                    "Big 5000 mAh Battery with 67W SUPERVOOC Charging",
                                    "64MP Triple Camera ( 64MP Main + 2MP Monochrome + 2MP Microscope ) with AI Color Portrait and Dual View Video | 32MP Front Camera",
                                    "6.72 inch (17.07cm) FHD+ Punch-hole 120Hz Display with 2400x1080 pixels. Large Screen to Body ratio of 91.4%"
                                ],
                                colour: ["Bold Gold"],
                                stock: "Out of stock",
                                stars: 3.9,
                                reviews: 814,
                                price: 24999,
                            },
                            {
                                id: 103,
                                category: "electronics",
                                subCategory: "phone",
                                productName: "Oppo Find X2 Smart Phone",
                                brand: "Oppo",
                                ModelName: "CPH2023",
                                os: "Android 10.0",
                                manufacturer: "OPPO MOBILES INDIA PVT",
                                images: {
                                    imgUrl1: "/images/mobilesImages/oppo/oppo_Find_X2/oppo_find_X2.png",
                                    imgUrl2: "/images/mobilesImages/oppo/oppo_Find_X2/oppo_find_X2_img1.jpg",
                                    imgUrl3: "/images/mobilesImages/oppo/oppo_Find_X2/oppo_find_X2_img2.jpg",
                                    imgUrl4: "/images/mobilesImages/oppo/oppo_Find_X2/oppo_find_X2_img3.jpg",
                                    imgUrl5: "/images/mobilesImages/oppo/oppo_Find_X2/oppo_find_X2_img4.jpg",
                                    imgUrl6: "/images/mobilesImages/oppo/oppo_Find_X2/oppo_find_X2_img5.jpg",
                                },
                                discription: "OPPO Find X2 (Black, 12GB RAM, 256GB Storage)",
                                about: [
                                    "48MP (Sony IMX586 Sensor) wide-angle lens (f/1.7 aperture) rear camera, 12MP (Sony IMX708 Sensor) ultra-wide-angle lens (f/2.2 aperture), 13MP (f/2.4 aperture) telephoto camera | 32MP front facing camera",
                                    "Memory, Storage & SIM: 12GB RAM (LPDDR5) | 256GB (UFS 3.0) internal memory | Dual Nano SIM",
                                    "Innovative 65W SuperVOOC flash charging brings the 4260 mAh battery to 40% in just 10 minutes, fully charging in 38 minutes providing talk-time of 37.8 hours and standby time of 378 hours",
                                ],
                                colour: ["Black"],
                                stock: "Out of stock",
                                stars: 3.9,
                                reviews: 814,
                                price: 60990,
                            },
                            {
                                id: 104,
                                category: "electronics",
                                subCategory: "phone",
                                productName: "Oppo A58 Smart Phone",
                                brand: "Oppo",
                                ModelName: "A58",
                                os: "Android 13.0",
                                manufacturer: "OPPO MOBILES INDIA PVT",
                                images: {
                                    imgUrl1: "/images/mobilesImages/oppo/oppo_A58/oppo_A58.png",
                                    imgUrl2: "/images/mobilesImages/oppo/oppo_A58/oppo_A58_img1.jpg",
                                    imgUrl3: "/images/mobilesImages/oppo/oppo_A58/oppo_A58_img2.jpg",
                                    imgUrl4: "/images/mobilesImages/oppo/oppo_A58/oppo_A58_img3.jpg",
                                    imgUrl5: "/images/mobilesImages/oppo/oppo_A58/oppo_A58_img4.jpg",
                                    imgUrl6: "/images/mobilesImages/oppo/oppo_A58/oppo_A58_img5.jpg",
                                },
                                discription: "OPPO A58 (Dazzling Green, 6GB RAM, 128GB Storage) | 5000 mAh Battery and 33W SUPERVOOC | 6.72 inch FHD+ Punch Hole Display | Dual Stereo Speakers",
                                about: [
                                    "6 GB RAM (+ RAM expansion up to 6GB) | 128 GB ROM | Expandable Upto 1TB | Dual Sim Slot",
                                    "Big 5000 mAh Battery with 33W SUPERVOOC Charging + Dual Stereo Speakers with Ultra Volume Mode",
                                    "50MP Rear AI Camera : OV50D, 1/2.88'' sensor, 0.612μm pixels; f/1.8, FOV 75.5°, 5P lens | 2MP Portrait Camera : OV02B1B, 1/5'' sensor, 1.75μm pixels; f/2.4; FOV 89.1°, 3P lens",
                                    "8MP Selfie Camera : OV08D, 1/4'' sensor, 1.12μm pixels; f/2.0; FOV 80°, 4P lens",
                                    "6.72 inch FHD+ Punch Hole Display with 2400x1080 pixels"
                                ],
                                colour: ["Dazzling Green"],
                                stock: "In stock",
                                stars: 3.2,
                                reviews: 22,
                                price: 14999,
                            },
                            {
                                id: 105,
                                category: "electronics",
                                subCategory: "phone",
                                productName: "Vivo Y27 Smart Phone",
                                brand: "Vivo",
                                ModelName: "Y27",
                                os: "FunTouch OS 13",
                                manufacturer: "vivo Mobile India Pvt Ltd",
                                images: {
                                    imgUrl1: "/images/mobilesImages/vivo/vivo_Y27/vivo_Y27.png",
                                    imgUrl2: "/images/mobilesImages/vivo/vivo_Y27/vivo_Y27_img1.jpg",
                                    imgUrl3: "/images/mobilesImages/vivo/vivo_Y27/vivo_Y27_img2.jpg",
                                    imgUrl4: "/images/mobilesImages/vivo/vivo_Y27/vivo_Y27_img3.jpg",
                                    imgUrl5: "/images/mobilesImages/vivo/vivo_Y27/vivo_Y27_img4.jpg",
                                    imgUrl6: "/images/mobilesImages/vivo/vivo_Y27/vivo_Y27_img5.jpg",
                                },
                                discription: "Vivo Y27 (Burgundy Black, 6GB RAM, 128GB Storage) with No Cost EMI/Additional Exchange Offers",
                                about: [
                                    "50MP+2MP Rear Camera | 8MP Selfie Camera",
                                    "16.86 cm (6.64 inch) FHD+ Sunlight Display",
                                    "Memory & SIM: 6GB RAM | 128GB internal memory",
                                    "44W flashCharge with 5000 mAh battery",
                                ],
                                colour: ["Burgundy Black"],
                                stock: "In stock",
                                stars: 4.1,
                                reviews: 548,
                                price: 14999,
                            },
                            {
                                id: 106,
                                category: "electronics",
                                subCategory: "phone",
                                productName: "Vivo V23 Smart Phone",
                                brand: "Vivo",
                                ModelName: "V23 Pro 5G",
                                os: "Android 12.0",
                                manufacturer: "vivo Mobile India Pvt Ltd",
                                images: {
                                    imgUrl1: "/images/mobilesImages/vivo/vivo_V23/vivo_V23_pro.png",
                                    imgUrl2: "/images/mobilesImages/vivo/vivo_V23/vivo_V23_pro_img1.jpg",
                                    imgUrl3: "/images/mobilesImages/vivo/vivo_V23/vivo_V23_pro_img2.jpg",
                                    imgUrl4: "/images/mobilesImages/vivo/vivo_V23/vivo_V23_pro_img3.jpg",
                                    imgUrl5: "/images/mobilesImages/vivo/vivo_V23/vivo_V23_pro_img4.jpg",
                                    imgUrl6: "/images/mobilesImages/vivo/vivo_V23/vivo_V23_pro_img5.jpg",
                                },
                                discription: "Vivo V23 Pro 5G (Stardust Black, 12GB RAM, 256GB Storage)",
                                about: [
                                    "12 GB RAM | 256 GB ROM",
                                    "16.66 cm (6.56 inch) Full HD+ Display",
                                    "108MP + 8MP + 2MP | 50MP + 8MP Dual Front Camera",
                                    "4300 mAh Lithium Battery",
                                    "Connector type: 3.5mm jack"
                                ],
                                colour: ["Black"],
                                stock: "In stock",
                                stars: 2.1,
                                reviews: 348,
                                price: 29499,
                            },
                            {
                                id: 107,
                                category: "electronics",
                                subCategory: "phone",
                                productName: "Vivo Y100A Smart Phone",
                                brand: "Vivo",
                                ModelName: "Y100A",
                                os: "Funtouch OS 13",
                                manufacturer: "vivo Mobile India Pvt Ltd",
                                images: {
                                    imgUrl1: "/images/mobilesImages/vivo/vivo_Y100A/vivo_Y100A.png",
                                    imgUrl2: "/images/mobilesImages/vivo/vivo_Y100A/vivo_Y100A_img1.jpg",
                                    imgUrl3: "/images/mobilesImages/vivo/vivo_Y100A/vivo_Y100A_img2.jpg",
                                    imgUrl4: "/images/mobilesImages/vivo/vivo_Y100A/vivo_Y100A_img3.jpg",
                                    imgUrl5: "/images/mobilesImages/vivo/vivo_Y100A/vivo_Y100A_img4.jpg",
                                    imgUrl6: "/images/mobilesImages/vivo/vivo_Y100A/vivo_Y100A_img5.jpg",
                                },
                                discription: "vivo Y100A 5G (Twilight Gold, 8GB RAM, 128GB Storage) with No Cost EMI/Additional Exchange Offers",
                                about: [
                                    "Triple 64MP+2MP+2MP Rear Camera | 16MP Selfie Camera",
                                    "16.20 cm (6.38 inch) FHD+ AMOLED Display",
                                    "Memory & SIM: 8GB RAM | 128GB internal memory",
                                    "4300 mAh Lithium Battery",
                                    "44W fast charging with 4500mAh battery"
                                ],
                                colour: ["Twilight Gold"],
                                stock: "In stock",
                                stars: 3.1,
                                reviews: 600,
                                price: 21999,
                            },
                            {
                                id: 108,
                                category: "electronics",
                                subCategory: "phone",
                                productName: "Vivo Y02T Smart Phone",
                                brand: "Vivo",
                                ModelName: "Y02t",
                                os: "FunTouch OS 13 (Android 13 edition)",
                                manufacturer: "vivo Mobile India Pvt Ltd",
                                images: {
                                    imgUrl1: "/images/mobilesImages/vivo/vivo_Y02t/vivo_Y02t.png",
                                    imgUrl2: "/images/mobilesImages/vivo/vivo_Y02t/vivo_Y02t_img1.jpg",
                                    imgUrl3: "/images/mobilesImages/vivo/vivo_Y02t/vivo_Y02t_img2.jpg",
                                    imgUrl4: "/images/mobilesImages/vivo/vivo_Y02t/vivo_Y02t_img3.jpg",
                                    imgUrl5: "/images/mobilesImages/vivo/vivo_Y02t/vivo_Y02t_img4.jpg",
                                    imgUrl6: "/images/mobilesImages/vivo/vivo_Y02t/vivo_Y02t_img5.jpg",
                                },
                                discription: "Vivo Y02t (Sunset Gold, 4GB RAM, 64GB Storage) with No Cost EMI/Additional Exchange Offers",
                                about: [
                                    "Front 5 MP / Rear 8 MP",
                                    "16.53 cm (6.51 inch) HD+ Eye Protection Screen",
                                    "Memory & SIM: 4GB RAM | 64GB internal memory",
                                    "10W fast charging with 5000mAh battery",
                                ],
                                colour: ["Sunset Gold"],
                                stock: "Out of stock",
                                stars: 3.9,
                                reviews: 502,
                                price: 8999,
                            },
                            {
                                id: 110,
                                category: "electronics",
                                subCategory: "phone",
                                productName: "Realme Narzo 60 Smart Phone",
                                brand: "Realme",
                                ModelName: "realme narzo 60 5G",
                                os: "Android 13.0",
                                manufacturer: "OPPO Mobiles India Pvt Ltd,",
                                images: {
                                    imgUrl1: "/images/mobilesImages/realme/realme_narzo_60/realme_narzo_60.png",
                                    imgUrl2: "/images/mobilesImages/realme/realme_narzo_60/realme_narzo_60_img1.jpg",
                                    imgUrl3: "/images/mobilesImages/realme/realme_narzo_60/realme_narzo_60_img2.jpg",
                                    imgUrl4: "/images/mobilesImages/realme/realme_narzo_60/realme_narzo_60_img3.jpg",
                                    imgUrl5: "/images/mobilesImages/realme/realme_narzo_60/realme_narzo_60_img4.jpg",
                                    imgUrl6: "/images/mobilesImages/realme/realme_narzo_60/realme_narzo_60_img5.jpg",
                                },
                                discription: "realme narzo 60 5G (Cosmic Black,8GB+256GB) | 90Hz Super AMOLED Display | Ultra Sharp 64 MP Camera | with 33W SUPERVOOC Charger",
                                about: [
                                    "Immerse yourself in a smooth and responsive visual experience with our vibrant 90Hz Super AMOLED display. ",
                                    "Embrace the sleekness of our ultra-slim design, measuring only 7.93mm in thickness. ",
                                    "Unleash your creativity and capture stunning street photography moments with our powerful 64 MP camera.",
                                ],
                                colour: ["Cosmic Black"],
                                stock: "In stock",
                                stars: 4.3,
                                reviews: 859,
                                price: 18499,
                            },
                            {
                                id: 111,
                                category: "electronics",
                                subCategory: "phone",
                                productName: "Realme Narzo 50i Smart Phone",
                                brand: "Realme",
                                ModelName: "realme narzo 50i",
                                os: "Android 11.0",
                                manufacturer: "OPPO Mobiles India Pvt Ltd,",
                                images: {
                                    imgUrl1: "/images/mobilesImages/realme/realme_narzo_50i/realme_narzo_50i.png",
                                    imgUrl2: "/images/mobilesImages/realme/realme_narzo_50i/realme_narzo_50i_img1.jpg",
                                    imgUrl3: "/images/mobilesImages/realme/realme_narzo_50i/realme_narzo_50i_img2.jpg",
                                    imgUrl4: "/images/mobilesImages/realme/realme_narzo_50i/realme_narzo_50i_img3.jpg",
                                    imgUrl5: "/images/mobilesImages/realme/realme_narzo_50i/realme_narzo_50i_img4.jpg",
                                    imgUrl6: "/images/mobilesImages/realme/realme_narzo_50i/realme_narzo_50i_img5.jpg",
                                },
                                discription: "realme narzo 50i (Carbon Black, 4GB RAM+64GB Storage) Octa Core Processor | 6.5 inch Large Display",
                                about: [
                                    "4 GB RAM | 64 GB ROM | Expandable Upto 256 GB",
                                    "16.51 cm (6.5 inch) HD+ Display | 88.7% Screen-to-body Ratio | LCD Multi-touch Display | 1600-by-720-pixel Resolution | 400 nits Max Brightness (Typical)",
                                    "8MP Primary Camera (f/2.0 Aperture,4P Lens,4x, Digital Zoom Panoramic View, Portrait Mode, Expert, Timelapse, HDR, Beauty, Filter | 5MP AI Selfie Camera (f/2.2 aperture, portrait Mode, AI Beauty, HDR, Face-Recognition, Filter)",
                                    "5000 mAh Massive Battery | Supports Ultra Saving Mode |",
                                    "Powerful Octa-core Processor | CPU: Octa-core CPU, up to 1.6GHz | GPU: IMG 8322"
                                ],
                                colour: ["Carbon Black"],
                                stock: "Out of stock",
                                stars: 5.0,
                                reviews: 1200,
                                price: 8799,
                            },
                            {
                                id: 112,
                                category: "electronics",
                                subCategory: "phone",
                                productName: "Realme Narzo N55 Smart Phone",
                                brand: "Realme",
                                ModelName: "realme narzo N55",
                                os: "Android 13.0",
                                manufacturer: "OPPO Mobiles India Pvt Ltd,",
                                images: {
                                    imgUrl1: "/images/mobilesImages/realme/realme_narzo_N55/realme_narzo_N55.png",
                                    imgUrl2: "/images/mobilesImages/realme/realme_narzo_N55/realme_narzo_N55_img1.jpg",
                                    imgUrl3: "/images/mobilesImages/realme/realme_narzo_N55/realme_narzo_N55_img2.jpg",
                                    imgUrl4: "/images/mobilesImages/realme/realme_narzo_N55/realme_narzo_N55_img3.jpg",
                                    imgUrl5: "/images/mobilesImages/realme/realme_narzo_N55/realme_narzo_N55_img4.jpg",
                                    imgUrl6: "/images/mobilesImages/realme/realme_narzo_N55/realme_narzo_N55_img5.jpg",
                                },
                                discription: "realme narzo N55 (Prime Blue, 6GB+128GB) 33W Segment Fastest Charging | Super High-res 64MP Primary AI Camera",
                                about: [
                                    "* With fast 33W SUPERVOOC charging, the realme narzo N55 charges up the massive 5000mAh battery from 0-50% in just 29 minutes, making your life super convenient and stress free.",
                                    " Super High-res 64MP primary AI camera allows you to shoot crisp and clear shots in any scenario with incredible detail. The flagship grade ProLight Imaging technology brings segment leading low light performance to the N55.",
                                    " Enjoy up to 12GB of Dynamic RAM made up from up to 6GB of onboard RAM and up to an additional 6GB of Dynamic RAM for next level multi tasking.",
                                    " Large 6.72” Full screen display on the narzo N55 provides a segment leading display with a centre punch hole display",
                                ],
                                colour: ["Prime Blue"],
                                stock: "In stock",
                                stars: 3.0,
                                reviews: 1108,
                                price: 12999,
                            },
                            {
                                id: 113,
                                category: "electronics",
                                subCategory: "phone",
                                productName: "Apple Iphone 13 Smart Phone",
                                brand: "Apple",
                                ModelName: "iPhone",
                                os: "iOS 14",
                                manufacturer: "Apple",
                                images: {
                                    imgUrl1: "/images/mobilesImages/iphone/apple_iphone_13/apple_iphone_13.png",
                                    imgUrl2: "/images/mobilesImages/iphone/apple_iphone_13/apple_iphone_13_img1.jpg",
                                    imgUrl3: "/images/mobilesImages/iphone/apple_iphone_13/apple_iphone_13_img2.jpg",
                                    imgUrl4: "/images/mobilesImages/iphone/apple_iphone_13/apple_iphone_13_img3.jpg",
                                    imgUrl5: "/images/mobilesImages/iphone/apple_iphone_13/apple_iphone_13_img4.jpg",
                                    imgUrl6: "/images/mobilesImages/iphone/apple_iphone_13/apple_iphone_13_img5.jpg",
                                },
                                discription: "Apple iPhone 13 (128GB) - Starlight",
                                about: [
                                    "15 cm (6.1-inch) Super Retina XDR display",
                                    "Cinematic mode adds shallow depth of field and shifts focus automatically in your videos",
                                    "Advanced dual-camera system with 12MP Wide and Ultra Wide cameras; Photographic Styles, Smart HDR 4, Night mode, 4K Dolby Vision HDR recording",
                                    "12MP TrueDepth front camera with Night mode, 4K Dolby Vision HDR recording"
                                ],
                                colour: ["Starlight"],
                                stock: "In stock",
                                stars: 4.6,
                                reviews: 17993,
                                price: 50999
                            },
                            {
                                id: 114,
                                category: "electronics",
                                subCategory: "phone",
                                productName: "Apple Iphone 15 Smart Phone",
                                brand: "Apple",
                                ModelName: "iPhone",
                                os: "iOS",
                                manufacturer: "Apple",
                                images: {
                                    imgUrl1: "/images/mobilesImages/iphone/apple_iphone_15/apple_iphone_15.png",
                                    imgUrl2: "/images/mobilesImages/iphone/apple_iphone_15/apple_iphone_15_img1.jpg",
                                    imgUrl3: "/images/mobilesImages/iphone/apple_iphone_15/apple_iphone_15_img2.jpg",
                                    imgUrl4: "/images/mobilesImages/iphone/apple_iphone_15/apple_iphone_15_img3.jpg",
                                    imgUrl5: "/images/mobilesImages/iphone/apple_iphone_15/apple_iphone_15_img4.jpg",
                                    imgUrl6: "/images/mobilesImages/iphone/apple_iphone_15/apple_iphone_15_img5.jpg",
                                },
                                discription: "Apple iPhone 15 (128 GB) - Blue",
                                about: [
                                    "DYNAMIC ISLAND COMES TO IPHONE 15 — Dynamic Island bubbles up alerts and Live Activities",
                                    "INNOVATIVE DESIGN — iPhone 15 features a durable color-infused glass and aluminum design. It’s splash, water, and dust resistant.",
                                    "48MP MAIN CAMERA WITH 2X TELEPHOTO — The 48MP Main camera shoots in super-high resolution.",
                                    "NEXT-GENERATION PORTRAITS — Capture portraits with dramatically more detail and color.",
                                ],
                                colour: ["Blue"],
                                stock: "In stock",
                                stars: 4.0,
                                reviews: 61,
                                price: 79900
                            },
                            {
                                id: 115,
                                category: "electronics",
                                subCategory: "phone",
                                productName: "Apple Iphone 15 proMax Smart Phone",
                                brand: "Apple",
                                ModelName: "iPhone 15 Pro Max",
                                os: "iOS",
                                manufacturer: "Apple",
                                images: {
                                    imgUrl1: "/images/mobilesImages/iphone/apple_iphone_15_proMax/apple_iphone_15_Promax.png",
                                    imgUrl2: "/images/mobilesImages/iphone/apple_iphone_15_proMax/apple_iphone_15_Promax_img1.jpg",
                                    imgUrl3: "/images/mobilesImages/iphone/apple_iphone_15_proMax/apple_iphone_15_Promax_img2.jpg",
                                    imgUrl4: "/images/mobilesImages/iphone/apple_iphone_15_proMax/apple_iphone_15_Promax_img3.jpg",
                                    imgUrl5: "/images/mobilesImages/iphone/apple_iphone_15_proMax/apple_iphone_15_Promax_img4.jpg",
                                    imgUrl6: "/images/mobilesImages/iphone/apple_iphone_15_proMax/apple_iphone_15_Promax_img5.jpg",
                                },
                                discription: "Apple iPhone 15 Pro Max (256 GB) - Blue Titanium",
                                about: [
                                    "FORGED IN TITANIUM — iPhone 15 Pro Max has a strong and light aerospace-grade titanium design with a textured matte-glass back.",
                                    "ADVANCED DISPLAY — The 6.7” Super Retina XDR display with ProMotion ramps up refresh rates to 120Hz when you need exceptional graphics performance.",
                                    "GAME-CHANGING A17 PRO CHIP — A Pro-class GPU makes mobile games feel so immersive, with rich environments and realistic characters.",
                                    "POWERFUL PRO CAMERA SYSTEM — Get incredible framing flexibility with 7 pro lenses.",
                                    "CUSTOMIZABLE ACTION BUTTON — Action button is a fast track to your favorite feature. Just set the one you want, like Silent mode, Camera, Voice Memo, Shortcut, and more. Then press and hold to launch the action."
                                ],
                                colour: ["Blue Titanium"],
                                stock: "In stock",
                                stars: 3.7,
                                reviews: 16,
                                price: 159900
                            },
                            {
                                id: 116,
                                category: "electronics",
                                subCategory: "phone",
                                productName: "Apple Iphone 15 Plus Smart Phone",
                                brand: "Apple",
                                ModelName: "iPhone 15 Plus",
                                os: "iOS",
                                manufacturer: "Apple",
                                images: {
                                    imgUrl1: "/images/mobilesImages/iphone/apple_iphone_15_plus/apple_iphone_15_plus.png",
                                    imgUrl2: "/images/mobilesImages/iphone/apple_iphone_15_plus/apple_iphone_15_plus_img1.jpg",
                                    imgUrl3: "/images/mobilesImages/iphone/apple_iphone_15_plus/apple_iphone_15_plus_img2.jpg",
                                    imgUrl4: "/images/mobilesImages/iphone/apple_iphone_15_plus/apple_iphone_15_plus_img3.jpg",
                                    imgUrl5: "/images/mobilesImages/iphone/apple_iphone_15_plus/apple_iphone_15_plus_img4.jpg",
                                    imgUrl6: "/images/mobilesImages/iphone/apple_iphone_15_plus/apple_iphone_15_plus_img5.jpg",
                                },
                                discription: "Apple iPhone 15 Plus (128 GB) - Green",
                                about: [
                                    "DYNAMIC ISLAND COMES TO IPHONE 15 — Dynamic Island bubbles up alerts and Live Activities",
                                    "INNOVATIVE DESIGN — iPhone 15 Plus features a durable color-infused glass and aluminum design. It’s splash, water, and dust resistant.",
                                    "48MP MAIN CAMERA WITH 2X TELEPHOTO — The 48MP Main camera shoots in super-high resolution.",
                                    "NEXT-GENERATION PORTRAITS — Capture portraits with dramatically more detail and color.",
                                    "POWERHOUSE A16 BIONIC CHIP — The superfast chip powers advanced features like computational photography, fluid Dynamic Island transitions, and Voice Isolation for phone calls."
                                ],
                                colour: ["Green"],
                                stock: "In stock",
                                stars: 4.2,
                                reviews: 36,
                                price: 89900
                            },
                            {
                                id: 301,
                                category: "electronics",
                                subCategory: "earbuds",
                                productName: "Oneplus Buds Z2 earbuds",
                                brand: "Oneplus",
                                ModelName: "BudsZ2",
                                images: {
                                    imgUrl1: "/images/ipodImages/onePlus/budsZ2/onePlus_Buds_Z2.png",
                                    imgUrl2: "/images/ipodImages/onePlus/budsZ2/onePlus_Buds_Z2_img1.jpg",
                                    imgUrl3: "/images/ipodImages/onePlus/budsZ2/onePlus_Buds_Z2_img2.jpg",
                                    imgUrl4: "/images/ipodImages/onePlus/budsZ2/onePlus_Buds_Z2_img3.jpg",
                                    imgUrl5: "/images/ipodImages/onePlus/budsZ2/onePlus_Buds_Z2_img4.jpg",
                                    imgUrl6: "/images/ipodImages/onePlus/budsZ2/onePlus_Buds_Z2_img5.jpg",
                                },
                                discription: "OnePlus Buds Z2 Bluetooth Truly Wireless in Ear Earbuds with mic, Active Noise Cancellation, 10 Minutes Flash Charge & Upto 38 Hours Battery [Matte Black]",
                                about:[
                                    "Active Noise Cancellation: Up to 40 dB noise cancelling with 2 modes - Faint (+/- 25dB) & Extreme (+/- 40 dB) through manual adjustment via OnePlus mobile or HeyMelody App.",
                                    "High Quality Sound: 11mm dynamic drivers acoustically tuned for bigger, bolder beats with razor-sharp treble & Dolby atmos support delivers immersive, true-to-life sound using industry leading spatial audio",
                                    "3-MIC ENC Call Noise Reduction: To keep your calls sounding smooth, the 3-MIC design trims down wind noise caused by air friction.",
                                    "Worry-free Battery Life: Enjoy up to 38 hours of music and a quick fast charging of 10 minutes for 5 hours of playtime.",
                                    "Built for Mobile Gaming: Your winning advantage starts here with latency as low as 94ms, with Pro Gaming mode activated"
                                ],
                                colour: ["Matte Black"],
                                connectivity: ["Wireless", "Bluetooth"],
                                stock: "In stock",
                                manufacturer: "OnePlus",
                                stars: 4.5,
                                reviews: 40,
                                price: 4999
                            },
                            {
                                id: 302,
                                category: "electronics",
                                subCategory: "earbuds",
                                productName: "Oneplus Nord Buds CE earbuds",
                                brand: "Oneplus",
                                ModelName: "Nord Buds CE",
                                images: {
                                    imgUrl1: "/images/ipodImages/onePlus/nordBudsCE/onePlus_Nord_Buds_CE.png",
                                    imgUrl2: "/images/ipodImages/onePlus/nordBudsCE/onePlus_Nord_Buds_CE_img1.jpg",
                                    imgUrl3: "/images/ipodImages/onePlus/nordBudsCE/onePlus_Nord_Buds_CE_img2.jpg",
                                    imgUrl4: "/images/ipodImages/onePlus/nordBudsCE/onePlus_Nord_Buds_CE_img3.jpg",
                                    imgUrl5: "/images/ipodImages/onePlus/nordBudsCE/onePlus_Nord_Buds_CE_img4.jpg",
                                    imgUrl6: "/images/ipodImages/onePlus/nordBudsCE/onePlus_Nord_Buds_CE_img5.jpg",
                                },
                                discription: "OnePlus Nord Buds CE Bluetooth Truly Wireless in Ear Earbuds.",
                                about:[],
                                Colour: ["Moonlight White"],
                                Connectivity: ["Wireless"],
                                Manufacturer: "OnePlus",
                                stars: 4.2,
                                stock: "In stock",
                                price: 2299
                            },
                            {
                                id: 303,
                                category: "electronics",
                                subCategory: "earbuds",
                                productName: "Oneplus Buds Pro 2R earbuds",
                                brand: "Oneplus",
                                ModelName: "Buds Pro",
                                images: {
                                    imgUrl1: "/images/ipodImages/onePlus/pro2R/onePlus_Buds_Pro_2R.png",
                                    imgUrl2: "/images/ipodImages/onePlus/pro2R/onePlus_Buds_Pro_2R_img1.jpg",
                                    imgUrl3: "/images/ipodImages/onePlus/pro2R/onePlus_Buds_Pro_2R_img2.jpg",
                                    imgUrl4: "/images/ipodImages/onePlus/pro2R/onePlus_Buds_Pro_2R_img3.jpg",
                                    imgUrl5: "/images/ipodImages/onePlus/pro2R/onePlus_Buds_Pro_2R_img4.jpg",
                                    imgUrl6: "/images/ipodImages/onePlus/pro2R/onePlus_Buds_Pro_2R_img5.jpg",
                                },
                                discription: "OnePlus Nord Buds 2r True Wireless in Ear Earbuds with Mic, 12.4mm Drivers, Playback:Upto 38hr case,4-Mic Design, IP55 Rating [Deep Grey].",
                                about:[
                                    "Seamless connectivity: Instantaneous pairing with OnePlus smartphone, as soon as you open the charging case lid",
                                    "Co-created with Dynaudio: Helps you achieve optimal listening experience. Smart Scene Noise Cancellation2.0 : Up to 48dB Ultra-wide frequency noise cancellation system with personalized ANC.",
                                    "Worry-free Battery Life: Up-to 40 Hours Battery with quick charging 10 minutes for 3 hours of use with ANC on.",
                                    "Powerful, Punchy Bass with clear vocals: Drop the bass and listen to clear vocals with dual 11mm + 6mm dual drivers, delivering a precisely boosted sound profile designed to move you.",
                                    "3Mic AI for better call and noise cancellation. IP55 Water, Dust and Sweat resistant."
                                ],
                                Colour: ["Misty White"],
                                Connectivity: ["Wireless, Bluetooth"],
                                Manufacturer: "OnePlus",
                                stars: 3.2,
                                stock: "In stock",
                                price: 9999
                            },
                            {
                                id: 304,
                                category: "electronics",
                                subCategory: "earbuds",
                                productName: "Oneplus Buds Pro earbuds",
                                brand: "Oneplus",
                                ModelName: "Buds Pro",
                                images:{
                                    imgUrl1: "/images/ipodImages/onePlus/budsPro/onePlus_Buds_Pro.png",
                                    imgUrl2: "/images/ipodImages/onePlus/budsPro/onePlus_Buds_Pro_img1.jpg",
                                    imgUrl3: "/images/ipodImages/onePlus/budsPro/onePlus_Buds_Pro_img2.jpg",
                                    imgUrl4: "/images/ipodImages/onePlus/budsPro/onePlus_Buds_Pro_img3.jpg",
                                    imgUrl5: "/images/ipodImages/onePlus/budsPro/onePlus_Buds_Pro_img4.jpg",
                                    imgUrl6: "/images/ipodImages/onePlus/budsPro/onePlus_Buds_Pro_img5.jpg",
                                },
                                discription: "OnePlus Buds Pro Bluetooth Truly Wireless in Ear Earbuds with mic, Smart Adaptive Noise Cancellation, 10 Minutes Warp Charge, Upto 38 Hours Battery, Zen Mode, Bluetooth 5.2v (Matte Black)",
                                about:[],
                                Colour: ["Matte Black"],
                                Connectivity: ["Wireless"],
                                Manufacturer: "OnePlus",
                                stars: 4.2,
                                stock: "In stock",
                                price: 2999
                            },
                            {
                                id: 305,
                                category: "electronics",
                                subCategory: "earbuds",
                                productName: "Oneplus Buds Pro2 earbuds",
                                brand: "Oneplus",
                                ModelName: "Buds Pro",
                                images:{
                                    imgUrl1: "/images/ipodImages/onePlus/budsPro2/onePlus_Buds_Pro_2.png",
                                    imgUrl2: "/images/ipodImages/onePlus/budsPro2/onePlus_Buds_Pro_2_img1.jpg",
                                    imgUrl3: "/images/ipodImages/onePlus/budsPro2/onePlus_Buds_Pro_2_img2.jpg",
                                    imgUrl4: "/images/ipodImages/onePlus/budsPro2/onePlus_Buds_Pro_2_img3.jpg",
                                    imgUrl5: "/images/ipodImages/onePlus/budsPro2/onePlus_Buds_Pro_2_img4.jpg",
                                    imgUrl6: "/images/ipodImages/onePlus/budsPro2/onePlus_Buds_Pro_2_img5.jpg",
                                },
                                discription: "OnePlus Buds Pro 2 Bluetooth Truly Wireless in Ear Earbuds with Spatial Audio Dynamic Head Tracking,co-Created with Dynaudio,Upto 48dB Adaptive Noise Cancellation,Upto 40Hrs Battery[Obsidian Black].",
                                about: [
                                    "Seamless connectivity: Instantaneous pairing with OnePlus smartphone, as soon as you open the charging case lid. ",
                                    "Spatial audio: Enjoy Spatial Audio with Dynamic Head Tracking feature that helps you experience sounds on a whole new level.",
                                    "Worry-free Battery Life: Up-to 40 Hours Battery with quick charging 10 minutes for 3 hours of use with ANC on.",
                                    "Powerful, Punchy Bass with clear vocals: Drop the bass and listen to clear vocals with dual 11mm + 6mm dual drivers, delivering a precisely boosted sound profile designed to move you."
                                ],
                                Colour: ["Obsidian Black", "Arbor Green"],
                                Connectivity: ["Wireless Technology"],
                                Manufacturer: "OnePlus",
                                stars: 4,
                                stock: "In stock",
                                price: 11999
                            },
                            {
                                id: 306,
                                category: "electronics",
                                subCategory: "earbuds",
                                productName: "Samsung Galaxy Bean Buds Live earbuds",
                                brand: "Samsung",
                                ModelName: "Galaxy Bean_Buds Live",
                                images:{
                                    imgUrl1: "/images/ipodImages/samsung/budsLive/samsung_Galaxy_Buds_Live.png",
                                    imgUrl2: "/images/ipodImages/samsung/budsLive/samsung_Galaxy_Buds_Live_img1.jpg",
                                    imgUrl3: "/images/ipodImages/samsung/budsLive/samsung_Galaxy_Buds_Live_img2.jpg",
                                    imgUrl4: "/images/ipodImages/samsung/budsLive/samsung_Galaxy_Buds_Live_img3.jpg",
                                    imgUrl5: "/images/ipodImages/samsung/budsLive/samsung_Galaxy_Buds_Live_img4.jpg",
                                    imgUrl6: "/images/ipodImages/samsung/budsLive/samsung_Galaxy_Buds_Live_img5.jpg",
                                },
                                discription: "Samsung Galaxy Buds Live Bluetooth Truly Wireless in Ear Earbuds with Mic, Upto 21 Hours Playtime, Mystic Black",
                                about:[
                                    "1 year warranty provided by the manufacturer from date of purchase",
                                    "Crystal clear voice & call quality with 3 mics & a Voice Pick Up unit",
                                    "Deep & spacious sound tuned by AKG. Sensors: Accelerometer, Gyro, Proximity, Hall, Touch, Grip, VPU",
                                    "Eye-catching design in a glossy finish that keeps you connected yet comfortable through the day"
                                ],
                                colour: ["Mystic Black"],
                                connectivity: ["Bluetooth"],
                                Manufacturer: "samsung",
                                stars: 4,
                                stock: "In stock",
                                reviews: 40,
                                price: 4790,
                            },
                            {
                                id: 307,
                                category: "electronics",
                                subCategory: "earbuds",
                                productName: "Samsung Galaxy Buds2 Pro earbuds",
                                brand: "Samsung",
                                ModelName: "Samsung Galaxy Buds2 Pro",
                                images:{
                                    imgUrl1: "/images/ipodImages/samsung/buds2Pro/samsung_Galaxy_Buds2_Pros.png",
                                    imgUrl2: "/images/ipodImages/samsung/buds2Pro/samsung_Galaxy_Buds2_Pro_img1.jpg",
                                    imgUrl3: "/images/ipodImages/samsung/buds2Pro/samsung_Galaxy_Buds2_Pro_img2.jpg",
                                    imgUrl4: "/images/ipodImages/samsung/buds2Pro/samsung_Galaxy_Buds2_Pro_img3.jpg",
                                    imgUrl5: "/images/ipodImages/samsung/buds2Pro/samsung_Galaxy_Buds2_Pro_img4.jpg",
                                    imgUrl6: "/images/ipodImages/samsung/buds2Pro/samsung_Galaxy_Buds2_Pro_img5.jpg",
                                },
                                discription: "Samsung Galaxy Buds2 Pro, Bluetooth Truly Wireless in Ear Earbuds with Noise Cancellation (Bora Purple, with Mic)",
                                about:[
                                    "24-bit Hi-Fi audio. The upgraded Samsung Seamless Codec encodes the full 24-bit audio and is decoded via Galaxy Buds2 Pro, maintaining that same 24-bit high-quality sound.",
                                    "Intelligent ANC puts your playlist in focus. With 3 high SNR (Signal-to-Noise Ratio) microphones, Galaxy Buds2 Pro track and eliminate more outside sound — even soft sounds like wind.",
                                    "Comfort fit. We redesigned the earbuds to be 15% smaller than Buds Pro to fit snugly in your ear",
                                    "360 AUDIO - Hear it like you're there. With Intelligent 360 Audio, the sound feels more realistic.",
                                    "Get up to 5 hrs of continuous playtime with ANC on and up to 18 hrs in the cradle. Galaxy Buds2 Pro run on Bluetooth v5.3 and are IPX7 water resistant."
                                ],
                                colour: ["Bora Purple"],
                                connectivity: ["Wireless"],
                                Manufacturer: "samsung",
                                stars: 4,
                                stock: "In stock",
                                reviews: 40,
                                price: 15990,
                            },
                            {
                                id: 308,
                                category: "electronics",
                                subCategory: "earbuds",
                                productName: "Samsung Galaxy Buds2 True earbuds",
                                brand: "Samsung",
                                ModelName: "Galaxy Buds2",
                                images:{
                                    imgUrl1: "/images/ipodImages/samsung/buds2True/samsung_Galaxy_Buds2_True.png",
                                    imgUrl2: "/images/ipodImages/samsung/buds2True/samsung_Galaxy_Buds2_True_img1.jpg",
                                    imgUrl3: "/images/ipodImages/samsung/buds2True/samsung_Galaxy_Buds2_True_img2.jpg",
                                    imgUrl4: "/images/ipodImages/samsung/buds2True/samsung_Galaxy_Buds2_True_img3.jpg",
                                    imgUrl5: "/images/ipodImages/samsung/buds2True/samsung_Galaxy_Buds2_True_img4.jpg",
                                    imgUrl6: "/images/ipodImages/samsung/buds2True/samsung_Galaxy_Buds2_True_img5.jpg",
                                },
                                discription: "SAMSUNG Galaxy Buds2 True Wireless Earbuds Noise Cancelling Ambient Sound Bluetooth Lightweight Comfort Fit Touch Control, International Version (Graphite)",
                                about:[
                                    "nternational Version, Offered with 30 Days Warranty - our Ears Never Had It So Good:",
                                    "Tune Out Noises, Tune In Voices: Active Noise Cancellation blocks out unwanted sounds, helping you keep your focus wherever you are",
                                    "Feels Good While Looking Good: Galaxy Buds2 have a comfortable, low profile design that's 10% smaller and lighter than Galaxy Buds+",
                                    "Hear Clearly, Speak Confidently: The earbuds’ 3 microphones and noise reduction technology ensures voices are transmitted crisply and clearly, whether you're chatting with a friend or leading a high stakes conference call",
                                    "Power Worthy of Your Longest Playlist: Indulge your love of music with a long-lasting battery that's up to the job ",
                                ],
                                colour: ["GRAPHITE"],
                                connectivity: ["Wireless", "Bluetooth 5.2"],
                                Manufacturer: "samsung",
                                stars: 4,
                                stock: "In stock",
                                reviews: 40,
                                price: 9490,
                            },
                            {
                                id: 309,
                                category: "electronics",
                                subCategory: "earbuds",
                                productName: "Samsung Galaxy Buds2 True earbuds",
                                brand: "Samsung",
                                ModelName: "Galaxy Buds2",
                                    images:{
                                    imgUrl1: "/images/ipodImages/samsung/buds2True/samsung_Galaxy_Buds2_True.png",
                                    imgUrl2: "/images/ipodImages/samsung/buds2True/samsung_Galaxy_Buds2_True_img1.jpg",
                                    imgUrl3: "/images/ipodImages/samsung/buds2True/samsung_Galaxy_Buds2_True_img2.jpg",
                                    imgUrl4: "/images/ipodImages/samsung/buds2True/samsung_Galaxy_Buds2_True_img3.jpg",
                                    imgUrl5: "/images/ipodImages/samsung/buds2True/samsung_Galaxy_Buds2_True_img4.jpg",
                                    imgUrl6: "/images/ipodImages/samsung/buds2True/samsung_Galaxy_Buds2_True_img5.jpg",
                                },
                                discription: "Samsung Galaxy Buds 2 | Active Noise Cancellation, Auto Switch Feature, Up to 20hrs Battery Life, (White)",
                                about:[

                                ],
                                colour: ["White"],
                                connectivity: ["Bluetooth 5.2"],
                                Manufacturer: "samsung",
                                stars: 4,
                                reviews: 40,
                                price: 6599,
                            },
                            {
                                id: 310,
                                category: "electronics",
                                subCategory: "earbuds",
                                productName: "Samsung Galaxy Buds Pro 2 earbuds",
                                brand: "Samsung",
                                ModelName: "Samsung Galaxy Buds Pro 2",
                                images:{
                                    imgUrl1: "/images/ipodImages/samsung/budsPro2/samsung_Galaxy_Buds_Pro2.png",
                                    imgUrl2: "/images/ipodImages/samsung/budsPro2/samsung_Galaxy_Buds_Pro2_img1.jpg",
                                    imgUrl3: "/images/ipodImages/samsung/budsPro2/samsung_Galaxy_Buds_Pro2_img2.jpg",
                                    imgUrl4: "/images/ipodImages/samsung/budsPro2/samsung_Galaxy_Buds_Pro2_img3.jpg",
                                    imgUrl5: "/images/ipodImages/samsung/budsPro2/samsung_Galaxy_Buds_Pro2_img4.jpg",
                                    imgUrl6: "/images/ipodImages/samsung/budsPro2/samsung_Galaxy_Buds_Pro2_img5.jpg",
                                },
                                discription: "SAMSUNG Galaxy Buds Pro 2 [2022] (SM-R510) - (Gray)",
                                about:[

                                ],
                                colour: ["Grey"],
                                connectivity: ["Wireless"],
                                Manufacturer: "samsung",
                                stars: 4,
                                reviews: 1916,
                                price: 21999,
                            },
                            {
                                id: 311,
                                category: "electronics",
                                subCategory: "earbuds",
                                productName: "Amazon basics True earbuds",
                                brand: "Amazon",
                                ModelName: "Amazon Basics",
                                images:{
                                    imgUrl1: "/images/ipodImages/amazon/basicsTrue/amazon_Basics_True.png",
                                    imgUrl2: "/images/ipodImages/amazon/basicsTrue/amazon_Basics_True_img1.jpg",
                                    imgUrl3: "/images/ipodImages/amazon/basicsTrue/amazon_Basics_True_img2.jpg",
                                    imgUrl4: "/images/ipodImages/amazon/basicsTrue/amazon_Basics_True_img3.jpg",
                                    imgUrl5: "/images/ipodImages/amazon/basicsTrue/amazon_Basics_True_img4.jpg",
                                    imgUrl6: "/images/ipodImages/amazon/basicsTrue/amazon_Basics_True_img5.jpg",
                                },
                                discription: "Amazon Basics True Wireless in-Ear Earbuds with Mic, Touch Control, IPX5 Water-Resistance, Bluetooth 5.3, Up to 36 Hours Play Time, Voice Assistance and Fast Charging (White)",
                                about:[

                                ],
                                colour: ["White - Orange"],
                                connectivity: ["Wireless"],
                                Manufacturer: "Amazon",
                                stars: 4,
                                reviews: 12,
                                price: 849,
                            },
                            {
                                id: 312,
                                category: "electronics",
                                subCategory: "earbuds",
                                productName: "Amazon Basics True earbuds",
                                brand: "Amazon",
                                ModelName: "Earbuds",
                                images:{
                                    imgUrl1: "/images/ipodImages/amazon/basicsTrue2/amazon_Basics_True.png",
                                    imgUrl2: "/images/ipodImages/amazon/basicsTrue2/amazon_Basics_True_img1.jpg",
                                    imgUrl3: "/images/ipodImages/amazon/basicsTrue2/amazon_Basics_True_img2.jpg",
                                    imgUrl4: "/images/ipodImages/amazon/basicsTrue2/amazon_Basics_True_img3.jpg",
                                    imgUrl5: "/images/ipodImages/amazon/basicsTrue2/amazon_Basics_True_img4.jpg",
                                    imgUrl6: "/images/ipodImages/amazon/basicsTrue2/amazon_Basics_True_img5.jpg",
                                },
                                discription: "Amazon Basics True Wireless in-Ear Earbuds with Mic, Low-Latency Gaming Mode, Touch Control, IPX5 Water-Resistance, Bluetooth 5.3, Up to 60 Hours Play Time, Voice Assistance and Fast Charging (Black)",
                                about:[

                                ],
                                colour: ["Black - Red"],
                                connectivity: ["Wireless"],
                                Manufacturer: "amazon",
                                stars: 4,
                                reviews: 202,
                                price: 1099,
                            },
                            {
                                id: 313,
                                category: "electronics",
                                subCategory: "earbuds",
                                productName: "Amazon Basics ABBTTWS1002 Bluetooth earbuds",
                                brand: "Amazon",
                                ModelName: "ABBTTWS1002",
                                images:{
                                    imgUrl1: "/images/ipodImages/amazon/basicsBluetooth/amazon_Basics_Bluetooth.png",
                                    imgUrl2: "/images/ipodImages/amazon/basicsBluetooth/amazon_Basics_Bluetooth_img1.jpg",
                                    imgUrl3: "/images/ipodImages/amazon/basicsBluetooth/amazon_Basics_Bluetooth_img2.jpg",
                                    imgUrl4: "/images/ipodImages/amazon/basicsBluetooth/amazon_Basics_Bluetooth_img3.jpg",
                                    imgUrl5: "/images/ipodImages/amazon/basicsBluetooth/amazon_Basics_Bluetooth_img4.jpg",
                                    imgUrl6: "/images/ipodImages/amazon/basicsBluetooth/amazon_Basics_Bluetooth_img5.jpg",
                                },
                                discription: "Amazon Basics Bluetooth 5.0 Truly Wireless in Ear Earbuds, Up to 38 Hours Playtime, IPX-5 Rated, Type-C Charging Case, Touch Controls, Voice Assistant, Optional Single Side Use for Calls, Blue",
                                about:[

                                ],
                                colour: ["Blue"],
                                connectivity: ["Wireless"],
                                Manufacturer: "amazon",
                                stars: 4,
                                reviews: 2884,
                                price: 899,
                            },
                            {
                                id: 314,
                                category: "electronics",
                                subCategory: "earbuds",
                                productName: "Amazon Basics True earbuds",
                                brand: "Amazon",
                                ModelName: "amazon basics",
                                images:{
                                    imgUrl1: "/images/ipodImages/amazon/basicsTrue3/amazon_Basics_True.png",
                                    imgUrl2: "/images/ipodImages/amazon/basicsTrue3/amazon_Basics_True_img1.jpg",
                                    imgUrl3: "/images/ipodImages/amazon/basicsTrue3/amazon_Basics_True_img2.jpg",
                                    imgUrl4: "/images/ipodImages/amazon/basicsTrue3/amazon_Basics_True_img3.jpg",
                                    imgUrl5: "/images/ipodImages/amazon/basicsTrue3/amazon_Basics_True_img4.jpg",
                                    imgUrl6: "/images/ipodImages/amazon/basicsTrue3/amazon_Basics_True_img5.jpg",
                                },
                                discription: "Amazon Basics True Wireless in-Ear Earbuds with Mic, Low-Latency Gaming Mode (Up to 50 ms), Touch Control, IPX7, Bluetooth 5.0, Up to 42 Hours Play Time, Voice Assistance and Fast Charging (White)",
                                about:[

                                ],
                                colour: ["BLACK & WHITE"],
                                connectivity: ["Wireless"],
                                Manufacturer: "amazon",
                                stars: 4,
                                reviews: 720,
                                price: 1099,
                            },
                            {
                                id: 315,
                                category: "electronics",
                                subCategory: "earbuds",
                                productName: "Amazon Basics True earbuds",
                                brand: "Amazon",
                                ModelName: "amazon basics",
                                images:{
                                    imgUrl1: "/images/ipodImages/amazon/basicsTrue4/amazon_Basics_True.png",
                                    imgUrl2: "/images/ipodImages/amazon/basicsTrue4/amazon_Basics_True_img1.jpg",
                                    imgUrl3: "/images/ipodImages/amazon/basicsTrue4/amazon_Basics_True_img2.jpg",
                                    imgUrl4: "/images/ipodImages/amazon/basicsTrue4/amazon_Basics_True_img3.jpg",
                                    imgUrl5: "/images/ipodImages/amazon/basicsTrue4/amazon_Basics_True_img4.jpg",
                                    imgUrl6: "/images/ipodImages/amazon/basicsTrue4/amazon_Basics_True_img5.jpg",
                                },
                                discription: "(Refurbished) AmazonBasics True Wireless in-Ear Earbuds with Mic, Touch Control, IPX5 Water-Resistance, Bluetooth 5.3, Up to 40 Hours Play Time, Voice Assistance and Fast Charging (Green and Black)",
                                about:[

                                ],
                                colour: ["Green and Black"],
                                connectivity: ["Wireless"],
                                Manufacturer: "amazon",
                                stars: 4,
                                reviews: 720,
                                price: 699,
                            },
                            {
                                id: 401,
                                category: "electronics",
                                subCategory: "watch",
                                productName: "Noise Pulse Smart Watch",
                                brand: "Noise",
                                ModelName: "Pulse",
                                images: {
                                    imgUrl1: "/images/smartWatch/noise/noise_pulse/noise_colorfit_pulse.png",
                                    imgUrl2: "/images/smartWatch/noise/noise_pulse/noise_colorfit_pulse_img1.jpg",
                                    imgUrl3: "/images/smartWatch/noise/noise_pulse/noise_colorfit_pulse_img2.jpg",
                                    imgUrl4: "/images/smartWatch/noise/noise_pulse/noise_colorfit_pulse_img3.jpg",
                                    imgUrl5: "/images/smartWatch/noise/noise_pulse/noise_colorfit_pulse_img4.jpg",
                                    imgUrl6: "/images/smartWatch/noise/noise_pulse/noise_colorfit_pulse_img5.jpg",
                                },
                                discription: "Noise ColorFit Pulse Grand Smart Watch with 1.69 inch HD Display, 60 Sports Modes, 150 Watch Faces, Spo2 Monitoring, Call Notification, Quick Replies to Text & Calls (Rose Pink)",
                                about:[
                                    "1.69 inch grand display: Get the rich immersive viewing experience on the 1.69 inch LCD display.;60 sports modes: Take your pick from a wide range of 60 sports modes.",
                                    "Instant charge: Now enjoy more than a day’s worth/25 hours of battery in just 15 minutes of charge.;150+ cloud-based & customisable watch faces:",
                                    "Noise Health suite: Get valuable insights about your health from Noise Health Suite featuring 24*7 heart rate, stress, blood oxygen, sleep monitor and menstrual cycle tracking.",
                                    "IP68 waterproof: Live your life the way you want to, thanks to the IP68 waterproof rating.;7-day battery:",
                                    "Compatible Devices: Smartphone; Connectivity Technology: Usb; Included Components: Smartwatch, Magnetic Charger, User Manual, Warranty Card; Item Type Name: Smartwatch"
                                ],
                                colour: ["Rose Pink"],
                                style: "ColorFit Pulse Grand",
                                stock: "In stock",
                                manufacturer: "Noise",
                                stars: 4.0,
                                reviews: 10958,
                                price: 1499
                            },
                            {
                                id: 402,
                                category: "electronics",
                                subCategory: "watch",
                                productName: "Noise Pulse 2 Smart Watch",
                                brand: "Noise",
                                ModelName: "Pulse",
                                images: {
                                    imgUrl1: "/images/smartWatch/noise/noise_pulse2/noise_pulse2_max.png",
                                    imgUrl2: "/images/smartWatch/noise/noise_pulse2/noise_pulse2_max_img1.jpg",
                                    imgUrl3: "/images/smartWatch/noise/noise_pulse2/noise_pulse2_max_img2.jpg",
                                    imgUrl4: "/images/smartWatch/noise/noise_pulse2/noise_pulse2_max_img3.jpg",
                                    imgUrl5: "/images/smartWatch/noise/noise_pulse2/noise_pulse2_max_img4.jpg",
                                    imgUrl6: "/images/smartWatch/noise/noise_pulse2/noise_pulse2_max_img5.jpg",
                                },
                                discription: "Noise ColorFit Pulse Grand Smart Watch with 1.69 inch HD Display, 60 Sports Modes, 150 Watch Faces, Spo2 Monitoring, Call Notification, Quick Replies to Text & Calls (Rose Pink)",
                                about:[
                                    "Massive 1.85 inch display: See everyday data clearly under the brightest sun on the 1.85'' TFT LCD that sports 550 nits of brightness and the highest screen-to-body ratio.",
                                    "BT calling: Talk directly to your loved ones from your wrist; manage calls, access your favourite contacts and dial from the dial pad.",
                                    "Tru Sync: Now connect with the world in a smart way, thanks to Tru Sync technology that ensures faster and stable connection and low power consumption.",
                                    "Smart DND: Take a break when you want to and get uninterrupted sleep time.",
                                    "Noise Health Suite: Get started on your fitness journey with a whole range of wellness features in Noise Health Suite and 100 sports modes to support you.",
                                    "NoiseFit app: Manage your day-to-day life better with the NoiseFit app at your disposal."
                                ],
                                colour: ["Black"],
                                style: "Modern",
                                stock: "In stock",
                                manufacturer: "Noise",
                                stars: 4.0,
                                reviews: 19938,
                                price: 1199
                            },
                            {
                                id: 403,
                                category: "electronics",
                                subCategory: "watch",
                                productName: "Noise Twist Round Dial Smart Watch",
                                brand: "Noise",
                                ModelName: "NoiseFit Twist",
                                images: {
                                    imgUrl1: "/images/smartWatch/noise/noise_twist/noise_round_dial.png",
                                    imgUrl2: "/images/smartWatch/noise/noise_twist/noise_round_dial_img1.jpg",
                                    imgUrl3: "/images/smartWatch/noise/noise_twist/noise_round_dial_img2.jpg",
                                    imgUrl4: "/images/smartWatch/noise/noise_twist/noise_round_dial_img3.jpg",
                                    imgUrl5: "/images/smartWatch/noise/noise_twist/noise_round_dial_img4.jpg",
                                    imgUrl6: "/images/smartWatch/noise/noise_twist/noise_round_dial_img5.jpg",
                                },
                                discription: "Noise Twist Round dial Smart Watch with Bluetooth Calling, 1.38 inch TFT Display, up-to 7 Days Battery, 100+ Watch Faces, IP68, Heart Rate Monitor, Sleep Tracking (Jet Black)",
                                about:[
                                    "1.38” TFT display: Featuring a vibrant round display and a stylish metallic finish, the smartwatch offers a premium on-screen experience.",
                                    "Tru SyncTM: Hassle-free pairing, stable connectivity and lower battery consumption combine to provide the most advanced calling experience.",
                                    "Noise Buzz: Manage calls directly from your wrist. Access your call logs, make calls from the dial pad and save up to 10 favourite contacts.",
                                    "Noise Health SuiteTM: Take better care of your daily health with a series of health monitoring tools – Blood oxygen monitor, Sleep monitor, 24x7 heart rate monitor, Stress measurement, Breathe practice & Female cycle tracker.",
                                    "100 sports modes: Indulge in the routine of your preference with several sports modes to choose from.",
                                    "Up to 7-day battery: Breeze through an entire week without charging with up to 7 days of battery life. Get up to 2 days of battery life when calling in enabled."
                                ],
                                colour: ["Black"],
                                style: "Modern",
                                screenSize: "1.38 Inches",
                                stock: "In stock",
                                manufacturer: "Noise",
                                stars: 3.9,
                                reviews: 10457,
                                price: 1299
                            },
                            {
                                id: 404,
                                category: "electronics",
                                subCategory: "watch",
                                productName: "Noise ColorFit Pulse 3 Smart Watch",
                                brand: "Noise",
                                ModelName: "ColorFit Pulse 3",
                                images: {
                                    imgUrl1: "/images/smartWatch/noise/noise_newly_pulse3/noise_newly_colorfit_pulse3.png",
                                    imgUrl2: "/images/smartWatch/noise/noise_newly_pulse3/noise_newly_colorfit_pulse3_img1.jpg",
                                    imgUrl3: "/images/smartWatch/noise/noise_newly_pulse3/noise_newly_colorfit_pulse3_img2.jpg",
                                    imgUrl4: "/images/smartWatch/noise/noise_newly_pulse3/noise_newly_colorfit_pulse3_img3.jpg",
                                    imgUrl5: "/images/smartWatch/noise/noise_newly_pulse3/noise_newly_colorfit_pulse3_img4.jpg",
                                    imgUrl6: "/images/smartWatch/noise/noise_newly_pulse3/noise_newly_colorfit_pulse3_img5.jpg",
                                },
                                discription: "Noise Newly Launched ColorFit Pulse 3 with 1.96 inch Biggest Display Bluetooth Calling Smart Watch, Premium Build, Auto Sport Detection & 170+ Watch Faces Smartwatch for Men & Women (Jet Black)",
                                about:[
                                    "1.96 inch TFT display: Immerse yourself in a truly exceptional smartwatch experience with a larger and improved display that boasts a thinner bezel, delivering an unmatched visual experience",
                                    "7-day battery: Whether you're on the go or at home, stay connected to the world without the need for constant charging",
                                    "NoiseFit app: Take charge of your fitness goals with the NoiseFit app - track your activity, complete challenges, compete with friends, and earn exclusive rewards and offers",
                                    "What’s in the box: ColorFit Pulse 3 smartwatch, charger, warranty card, and a user manual",
                                ],
                                colour: ["Black"],
                                style: "Pulse 3",
                                screenSize: "1.96 Inches",
                                stock: "In stock",
                                manufacturer: "Noise",
                                stars: 4.0,
                                reviews: 11546,
                                price: 1489
                            },
                            {
                                id: 405,
                                category: "electronics",
                                subCategory: "watch",
                                productName: "Noise ColorFit Ultra 3 Bluetooth Smart Watch",
                                brand: "Noise",
                                ModelName: "ColorFit Ultra 3",
                                images: {
                                    imgUrl1: "/images/smartWatch/noise/noise_ultra3/noise_ultra3.png",
                                    imgUrl2: "/images/smartWatch/noise/noise_ultra3/noise_ultra3_img1.jpg",
                                    imgUrl3: "/images/smartWatch/noise/noise_ultra3/noise_ultra3_img2.jpg",
                                    imgUrl4: "/images/smartWatch/noise/noise_ultra3/noise_ultra3_img3.jpg",
                                    imgUrl5: "/images/smartWatch/noise/noise_ultra3/noise_ultra3_img4.jpg",
                                    imgUrl6: "/images/smartWatch/noise/noise_ultra3/noise_ultra3_img5.jpg",
                                },
                                discription: "Noise ColorFit Ultra 3 Bluetooth Calling Smart Watch with Biggest 1.96 inch AMOLED Display, Premium Metallic Build, Functional Crown, Gesture Control with Metallic Strap (Glossy Silver: Elite Edition)",
                                about:[
                                    "1.96” (4.9 cm) AMOLED display - See life unfold on a bigger canvas.",
                                    "7-day battery life (2 days with calling) - Become unstoppable with a watch that powers up completely after only 2 hours of charging.",
                                    "NoiseFit app - Track your activity and stay on top of your fitness goals with the NoiseFit app. Complete challenges, compete with friends and earn exclusive offers and rewards.",
                                    "Equipped with MEMS Microphone for calling clarity.",
                                    "Features to love: - Advanced Bluetooth calling powered by Tru SyncTM for crystal clear calling. - Functional crown for effortless navigation. - Always On Display for easy accessibility.",
                                    "What’s in the box - smartwatch, charger, warranty card, user manual, toolkit for strap size adjustment (for Elite edition watches only)"
                                ],
                                colour: ["Glosy Silver"],
                                style: "Metal Strap",
                                screenSize: "1.96 Inches",
                                stock: "In stock",
                                manufacturer: "Noise",
                                stars: 4.0,
                                reviews: 10719,
                                price: 3199
                            },
                            {
                                id: 416,
                                category: "electronics",
                                subCategory: "mixer",
                                productName: "Philips HL7756/00 Mixer Grinder",
                                brand: "PHILIPS",
                                ModelName: "Philips HL7756/00",
                                images: {
                                    imgUrl1: "/images/mixerImages/philips/philips_HL7756_00/philips_HL7756.png",
                                    imgUrl2: "/images/mixerImages/philips/philips_HL7756_00/philips_HL7756_img1.jpg",
                                    imgUrl3: "/images/mixerImages/philips/philips_HL7756_00/philips_HL7756_img2.jpg",
                                    imgUrl4: "/images/mixerImages/philips/philips_HL7756_00/philips_HL7756_img3.jpg",
                                    imgUrl5: "/images/mixerImages/philips/philips_HL7756_00/philips_HL7756_img4.jpg",
                                    imgUrl6: "/images/mixerImages/philips/philips_HL7756_00/philips_HL7756_img5.jpg",
                                },
                                discription: "Philips HL7756/00 Mixer Grinder 750 Watt, 3 Stainless Steel Multipurpose Jars with 3 Speed Control and Pulse function (Black)",
                                about:[
                                    "Motor Warranty: 5 Years; Product Warranty: 2 Years",
                                    "No of Jars: 3; Jar Size: Wet Jar (1.5 Litres), Multipurpose Jar (1 Litre), Chutney Jar (0.3 Litres); Jar Material: Stainless Steel; Body Material: ABS; Blade Material: Stainless Steel; Speed Control: 3 Speed Control + Pulse",
                                    "Wattage: 750 W; Voltage: 230 V",
                                    "Burning smell during first few usage is normal due to varnish coating on motor and will stop after few usage cycles. ",
                                    "This product does not require installation. Please allow the motor to cool for some time between product uses.",
                                    "New and powerful 750 W Turbo Motor, with advanced air ventilation & sturdy coupler, allows 25 minutes* continuous grinding even for tough ingredients like black gram dal."
                                ],
                                colour: ["black"],
                                blade_material: "Stainless Steel",
                                capacity:	"1500 Milliliters",
                                stock: "In stock",
                                manufacturer: "Philips",
                                stars: 4.0,
                                reviews: 29468,
                                price: 3999
                            },
                            {
                                id: 417,
                                category: "electronics",
                                subCategory: "mixer",
                                productName: "Philips HL7720/00 Mixer Grinder",
                                brand: "PHILIPS",
                                ModelName: "Philips HL7720/00",
                                images: {
                                    imgUrl1: "/images/mixerImages/philips/philips_HL7720/philips_HL7720.png",
                                    imgUrl2: "/images/mixerImages/philips/philips_HL7720/philips_HL7720_img1.jpg",
                                    imgUrl3: "/images/mixerImages/philips/philips_HL7720/philips_HL7720_img2.jpg",
                                    imgUrl4: "/images/mixerImages/philips/philips_HL7720/philips_HL7720_img3.jpg",
                                    imgUrl5: "/images/mixerImages/philips/philips_HL7720/philips_HL7720_img4.jpg",
                                    imgUrl6: "/images/mixerImages/philips/philips_HL7720/philips_HL7720_img5.jpg",
                                },
                                discription: "Philips HL 7720 750-Watt Mixer Grinder with 3 Jars (Multicolour)",
                                about:[
                                    "Wattage: 750 W; Voltage: 230 V;No of Jars: 3; Jar Size: Wet Jar (1.5 Litre), Multipurpose Jar (1 Litre), Chutney Jar (0.4 Litre) ; Jar Material: Stainless Steel; Body Material: ABS; Blade Material: Stainless Steel; Speed Control: 4 Speed Control",
                                    "Burning smell during first few usage is normal due to varnish coating on motor and will stop after few usage cycles. Your mixer grinder's powerful motor may make some noise.",
                                    "Great grinding performance with 750W motor, advanced blades to cut the toughest ingredients with ease and auto cut off protection fro safety of mixer motor life",
                                    "Includes: Mixer Grinder, Chutney Jar, Multipurpose Jar, Wet Jar and Spatula",
                                ],
                                colour: ["red, white, grey"],
                                blade_material: "Stainless Steel",
                                capacity: "1.5 litres",
                                stock: "In stock",
                                manufacturer: "Philips",
                                stars: 4.1,
                                reviews: 4856,
                                price: 3349
                            },
                            {
                                id: 418,
                                category: "electronics",
                                subCategory: "mixer",
                                productName: "Philips HL7707/00 Mixer Grinder",
                                brand: "PHILIPS",
                                ModelName: "Philips HL7707/00",
                                images: {
                                    imgUrl1: "/images/mixerImages/philips/philips_3in1/philips_HL7707_3in1.png",
                                    imgUrl2: "/images/mixerImages/philips/philips_3in1/philips_HL7707_3in1_img1.jpg",
                                    imgUrl3: "/images/mixerImages/philips/philips_3in1/philips_HL7707_3in1_img2.jpg",
                                    imgUrl4: "/images/mixerImages/philips/philips_3in1/philips_HL7707_3in1_img3.jpg",
                                    imgUrl5: "/images/mixerImages/philips/philips_3in1/philips_HL7707_3in1_img4.jpg",
                                    imgUrl6: "/images/mixerImages/philips/philips_3in1/philips_HL7707_3in1_img5.jpg",
                                },
                                discription: "PHILIPS Mixer Grinder 3-in-1 750 Watt (Mixer Grinder + Juicer + Food Processor) 4 Jar, (HL7707/00)",
                                about:[
                                    "Motor Warranty: 5 Years; Product Warranty: 2 Years.Frequency : 50 Hz",
                                    "Powerful 750W motor with compact set-up fits most kitchen requirements and takes minimum storage space,with Gear Drive technology that supports food processing, Includes Mixer Grinder, ChefPro Bowl, Chutney Jar, Multipurpose Jar, Wet Jar, Pulp Extractor, chopping attachement, Fine shredding tool, Fine slicing tool, Grating tool and Kneading tool",
                                    "Wattage: 750 W; Voltage: 230 V; Revolution: 20.000 rpm (max)",
                                    "No of Jars: 4; Jar Size: ChefPro Jar (2.2 Litres), Wet Jar (1.5 L), Multipurpose Jar (1 Litre), Chutney Jar (0.5 Litre); Jar Material: Stainless Steel; Body Material: ABS; Blade Material: Stainless Steel; Speed Control: 3 Speed Control Motor + Pulse",
                                    "Leak-proof jars, easy-to-assemble accessories, PowerChop for superior chopping and special disc inserts for slicing and shredding allows for finest mixing, grinding, chopping, grating, slicing and atta kneading",
                                ],
                                colour: ["white, purple"],
                                blade_material: "Stainless Steel",
                                capacity: "2.2 litres",
                                stock: "In stock",
                                manufacturer: "Philips",
                                stars: 4.1,
                                reviews: 5216,
                                price: 9199
                            },
                            {
                                id: 419,
                                category: "electronics",
                                subCategory: "mixer",
                                productName: "Philips HL7505/02 Mixer Grinder",
                                brand: "PHILIPS",
                                ModelName: "Philips HL7505/02",
                                images: {
                                    imgUrl1: "/images/mixerImages/philips/philips_HL7505/philips_HL7505.png",
                                    imgUrl2: "/images/mixerImages/philips/philips_HL7505/philips_HL7505_img1.jpg",
                                    imgUrl3: "/images/mixerImages/philips/philips_HL7505/philips_HL7505_img2.jpg",
                                    imgUrl4: "/images/mixerImages/philips/philips_HL7505/philips_HL7505_img3.jpg",
                                    imgUrl5: "/images/mixerImages/philips/philips_HL7505/philips_HL7505_img4.jpg",
                                    imgUrl6: "/images/mixerImages/philips/philips_HL7505/philips_HL7505_img5.jpg",
                                },
                                discription: "Philips HL7505/02 Mixer Grinder, 500W Endura Motor with rapid cool motor technology, 3 heavy duty and leak proof Jars",
                                about:[
                                    "500 Watts Endura Motor : Unique motor design for longer life. It is designed for lower temperature rise during continuous grinding",
                                    "Rapid cool Motor Technology : Advanced air ventilation for faster motor cooling",
                                    "Unbreakable blades : Tough grade SS 304 steel for longer life of blades",
                                    "Heavy duty jars :Superior grade thick jars to sustain tough grinding. 1.25 L Wet Jar, 0.75 L Dry Jar & 0.3 L Chutney jar",
                                    "Leak Proof Jars : Double Flap thick gaskets to avoid spillage while grinding",
                                ],
                                colour: ["red, purple"],
                                blade_material: "Stainless Steel",
                                capacity: "1.2 litres",
                                stock: "In stock",
                                manufacturer: "Philips",
                                stars: 4.2,
                                reviews: 3641,
                                price: 3199
                            },
                            {
                                id: 420,
                                category: "electronics",
                                subCategory: "mixer",
                                productName: "Philips HL7756/02 Mixer Grinder",
                                brand: "PHILIPS",
                                ModelName: "Philips HL7756/02",
                                images: {
                                    imgUrl1: "/images/mixerImages/philips/philips_HL7756_02/philips_HL7756.png",
                                    imgUrl2: "/images/mixerImages/philips/philips_HL7756_02/philips_HL7756_img1.jpg",
                                    imgUrl3: "/images/mixerImages/philips/philips_HL7756_02/philips_HL7756_img2.jpg",
                                    imgUrl4: "/images/mixerImages/philips/philips_HL7756_02/philips_HL7756_img3.jpg",
                                    imgUrl5: "/images/mixerImages/philips/philips_HL7756_02/philips_HL7756_img4.jpg",
                                    imgUrl6: "/images/mixerImages/philips/philips_HL7756_02/philips_HL7756_img5.jpg",
                                },
                                discription: "PHILIPS HL7756/02 750W Mixer Grinder, Red",
                                about:[
                                    "Power: 750 watts. Specialized blades for smooth grinding",
                                    "Includes: Mixer grinder, Jar1 (1.5L), Jar2 (1L) and Jar3 (0.3L)",
                                    "Advanced air ventilation system",
                                    "New turbo powerful motor",
                                    "The coupler is made of tougher plastic material for firm engagement between the jars and the body which ensures continuous grinding performance, while you focus on your cooking",
                                ],
                                colour: ["red"],
                                blade_material: "Stainless Steel",
                                capacity: "1.5 litres",
                                stock: "In stock",
                                manufacturer: "Philips",
                                stars: 3.2,
                                reviews: 365,
                                price: 4275
                            },


                        ]

export default database;
